### ISSUE TITLE
detr_resnet50.pth file was missing from the Baidu link

### ISSUE THREAD

**Issue by NikhilChowdary-MCW** [DataXujing/TensorRT-DETR#1]
Hi @DataXujing, thanks for your efforts in creating this package.
I tried to implement this package by downloading the detr_resnet50.pth file from the Pan Baidu links that were provided in the README. It looks like the file was not present in that folder. Can you please let me know. Thank You

**Comment by DataXujing** [comment]
We only provide the onnx model,  you can use your own training model, and then modify the relevant parameters in the code

**Comment by NikhilChowdary-MCW** [comment]
Thanks for your reply. 
I have regenerated the ONNX model from the original repo and applied the ONNX-Simplified as mentioned in the previous threads and got this error (Same as you posted in the readme)
![hello](https://user-images.githubusercontent.com/76027580/125744218-24ef9ad9-e371-4990-94fe-730adc7e83a5.PNG)

So can I know the next step after this? Do I need to apply graphsurgeon or polygraph? Thank you

**Comment by DataXujing** [comment]
The version of tensorrt is consistent with this project?

**Comment by NikhilChowdary-MCW** [comment]
At present we are using 7.1.3.1 in the Xavier machine. 

![version](https://user-images.githubusercontent.com/76027580/125749355-f593dc12-011c-47e6-a017-557a65c9425b.PNG)

Will this version supports?

**Comment by DataXujing** [comment]
It is recommended to use the version above 7.2. The lower version will have the meylin error bug

**Comment by NikhilChowdary-MCW** [comment]
Sure, I will try to do that. Thank you.
